// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type AuthResponse struct {
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
	User    *User   `json:"user,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type TravelPreferences struct {
	ID                  string   `json:"id"`
	UserID              string   `json:"userId"`
	PreferredActivities []string `json:"preferredActivities,omitempty"`
	TravelStyle         *string  `json:"travelStyle,omitempty"`
	LanguagesSpoken     []string `json:"languagesSpoken,omitempty"`
	UpdatedAt           string   `json:"updatedAt"`
}

type UpdateProfileInput struct {
	FirstName      *string  `json:"firstName,omitempty"`
	LastName       *string  `json:"lastName,omitempty"`
	ProfilePicture *string  `json:"profilePicture,omitempty"`
	Bio            *string  `json:"bio,omitempty"`
	Interests      []string `json:"interests,omitempty"`
}

type UpdateTravelPreferencesInput struct {
	PreferredActivities []string `json:"preferredActivities,omitempty"`
	TravelStyle         *string  `json:"travelStyle,omitempty"`
	LanguagesSpoken     []string `json:"languagesSpoken,omitempty"`
}

type User struct {
	ID             string   `json:"id"`
	Email          string   `json:"email"`
	FirstName      *string  `json:"firstName,omitempty"`
	LastName       *string  `json:"lastName,omitempty"`
	ProfilePicture *string  `json:"profilePicture,omitempty"`
	Bio            *string  `json:"bio,omitempty"`
	Interests      []string `json:"interests,omitempty"`
	CreatedAt      string   `json:"createdAt"`
	UpdatedAt      string   `json:"updatedAt"`
}

type UserProfile struct {
	User              *User              `json:"user"`
	TravelPreferences *TravelPreferences `json:"travelPreferences,omitempty"`
}
