package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"

	"github.com/karthickgandhiTV/travel-social-backend/internal/auth"
)

// UpdateProfile updates the user's profile
func (r *mutationResolver) UpdateProfile(ctx context.Context, input UpdateProfileInput) (*User, error) {
	userID, err := auth.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	return r.UserService.UpdateProfile(ctx, userID, input)
}

// UpdateTravelPreferences updates the user's travel preferences
func (r *mutationResolver) UpdateTravelPreferences(ctx context.Context, input UpdateTravelPreferencesInput) (*TravelPreferences, error) {
	userID, err := auth.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	return r.UserService.UpdateTravelPreferences(ctx, userID, input)
}

// Me returns the currently authenticated user
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	userID, err := auth.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	return r.UserService.GetUserByID(ctx, userID)
}

// User returns a user by ID
func (r *queryResolver) User(ctx context.Context, id string) (*User, error) {
	// Check authentication
	_, err := auth.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	return r.UserService.GetUserByID(ctx, id)
}

// SearchUsers searches for users based on the provided query
func (r *queryResolver) SearchUsers(ctx context.Context, query string) ([]*User, error) {
	// Check authentication
	_, err := auth.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	return r.UserService.SearchUsers(ctx, query)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
